Update Dockerfile
On newer versions of Docker you need to add the trailing slash in order to build. Otherwise build will fail with this error code: 

Step 3/14 : COPY package.json package-lock.json .
When using COPY with more than one source file, the destination must be a directory and end with a /
ERROR: Service 'app' failed to build : Build failed